jwt:
  secret-key: mdvGWlxFwnjycwNDye9RldG+34lQUUfTZy7R5C8Ui8GZMen9721DgNg6OhpZS6EAZ9raXNfknYMxPV+rXdNz0w==
spring:
  security:
    rate-limiting:
      max-requests: 100
      interval-minutes: 1
      max-violations: 5
      ip-blacklist:
        temp-block-duration-minutes: 15
    oauth2:
      client:
        registration:
          google:
            client-id: 1077962168001-kpu3jsintt2ie7as7128ovp3dv3nvmsk.apps.googleusercontent.com
            client-secret: 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
            scope: email,profile
          facebook:
            client-id: 123456789012345
            client-secret: d61d20dad8389ea6bd1da52d8d993fabf51d2ed
            scope: email,public_profile
          github:
            client-id: Ov23lioE6eUGI5ZUdCqi
            client-secret: 8d61d20dad8389ea6bd1da52d8d993fabf51d2ed
            scope: read:user,user:email
  profiles:
    active: prod


---
spring:

  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:file:./data/interview_db
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-console

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://localhost:5432/comparison
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
